import type { Metadata } from "next";
import "@/app/globals.css";
import AuthInitializer from "@/components/layout/authInitializer";

export const metadata: Metadata = {
  title: "Lumina Clean",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthInitializer />
      <body>{children}</body>
    </html>
  );
}
